# Generated by Django 4.0.5 on 2022-07-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('DNI', models.IntegerField(max_length=10)),
                ('edad', models.IntegerField(max_length=3)),
            ],
        ),
    ]
